# Generated by Django 4.0 on 2021-12-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descritption',
            new_name='description',
        ),
    ]
